### ISSUE TITLE
QGIS minimum version

### ISSUE THREAD

**Issue by Gustry** [opengisch/qgis_trackable_project_files#11]
Thanks for the update this weekend about the plugin.

Is the plugin expected to work on QGIS 3.4?
I remember seeing some fixes in QGIS 3.6 and above.

Does the plugin works better with a specific QGIS version?

Related metadata: https://github.com/opengisch/qgis_trackable_project_files/blob/master/trackable_project_files/metadata.txt#L5 where it's written QGIS 3.0.

**Comment by m-kuhn** [comment]
3.6 has some patches to make the project file format itself more stable too, so this plugin is best served with 3.4, but probably runs fine with 3.4 as well.

**Comment by Gustry** [comment]
> 3.6 has some patches to make the project file format itself more stable too, so this plugin is best served with 3.4, but probably runs fine with 3.4 as well.

I guess you should have written `best served with 3.6` ;-)

Maybe the documentation needs to be updated?

**Comment by m-kuhn** [comment]
Sounds like a very good proposal, would you mind doing a PR?
